# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ae138e301a3dd467e7f1a69dbb2a87d942dc7d779a1b3888870af701a08cbb9188f753c5ae7e4189308d2a1cf200db3bd724278bcc1c8d673f5d53867ec4c7d

test:
  secret_key_base: 0423058fbe21402d316e58c5e982a589e34f953b629e533a946d891ef8d33a9f9da33ffbc3e3943534fe854775a8804dcb93090fa54ee09f466da14b09da736a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
